name: Run Tests and Publish Allure Report

on:
  push:
    branches: [main]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Pull todo-app image
        run: docker pull jackn47/todo-app:latest

      - name: Run todo-app container
        run: docker run -d -p 8080:4242 --name todo-app jackn47/todo-app:latest

      - name: Wait for app to start
        run: sleep 5

      - name: Run tests
        run: mvn clean test

      - name: Generate Allure Report (CLI)
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: target/allure-results
          allure_report: target/allure-report
          allure_history: allure-history

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: target/allure-report