name: Run API & WS Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Set up Docker
        run: docker --version

      - name: Pull todo-app image
        run: docker pull jackn47/todo-app:latest

      - name: Run todo-app container
        run: docker run -d -p 8080:4242 --name todo-app jackn47/todo-app:latest

      - name: Wait for app to start
        run: sleep 5

      - name: Run tests
        run: mvn clean test

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Send Telegram notification if tests failed
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="Тесты не прошли в репозитории *${{ github.repository }}* на ветке *${{ github.ref_name }}*. Проверь пайплайн: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            -d parse_mode=Markdown

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin